# ---------------------------------------------------------------------------
# netproc timing constraints -- five asynchronous domains.
#
# The clock block below is generated by tools/clocks.py from the `clocks` list
# in config.json: a create_clock per master, a create_generated_clock per
# divider, and the set_clock_groups that keeps the crossings out of setup
# analysis. Without that last one every crossing reports as an enormous
# violation and swamps the TNS shares the portfolio ranks on.
# ---------------------------------------------------------------------------
@ASTRA_CLOCK_DEFS@

foreach c [all_clocks] {
    set_clock_uncertainty 0.05 $c
    set_clock_transition  0.05 $c
}

# OpenSTA 3.1.0 cannot parse a bus subscript in a get_ports pattern
# (`get_ports {rx_byte[*]}` dies with a bare `Error: stoi`), so ports are
# selected by walking the collection and matching in Tcl. See HANDOFF.md §7.
proc astra_ports {collection bases} {
    set out {}
    foreach p $collection {
        set n [get_full_name $p]
        foreach b $bases {
            if {$n eq $b || [string match "${b}\[*" $n]} { lappend out $p; break }
        }
    }
    return $out
}

set all_in  [all_inputs]
set all_out [all_outputs]

set_input_delay  -clock clk_rx    [expr {@CLK_PERIOD:clk_rx@ * 0.15}] \
    [astra_ports $all_in {rx_valid rx_byte}]
set_input_delay  -clock clk_parse [expr {@CLK_PERIOD:clk_parse@ * 0.15}] \
    [astra_ports $all_in {parse_req}]
set_input_delay  -clock clk_look  [expr {@CLK_PERIOD:clk_look@ * 0.15}] \
    [astra_ports $all_in {look_search look_tag}]
set_input_delay  -clock clk_xfrm  [expr {@CLK_PERIOD:clk_xfrm@ * 0.15}] \
    [astra_ports $all_in {xfrm_valid xfrm_data xfrm_rot}]
set_input_delay  -clock clk_tx    [expr {@CLK_PERIOD:clk_tx@ * 0.15}] \
    [astra_ports $all_in {tx_valid tx_in}]

set_output_delay -clock clk_rx    [expr {@CLK_PERIOD:clk_rx@ * 0.15}] \
    [astra_ports $all_out {rx_crc rx_frame_ok rx_status}]
set_output_delay -clock clk_parse [expr {@CLK_PERIOD:clk_parse@ * 0.15}] \
    [astra_ports $all_out {parse_grant}]
set_output_delay -clock clk_look  [expr {@CLK_PERIOD:clk_look@ * 0.15}] \
    [astra_ports $all_out {look_idx look_hit}]
set_output_delay -clock clk_xfrm  [expr {@CLK_PERIOD:clk_xfrm@ * 0.15}] \
    [astra_ports $all_out {xfrm_out xfrm_par}]
set_output_delay -clock clk_tx    [expr {@CLK_PERIOD:clk_tx@ * 0.15}] \
    [astra_ports $all_out {tx_sum}]

set_input_transition 0.05 [astra_ports $all_in {rx_valid rx_byte parse_req look_search look_tag xfrm_valid xfrm_data xfrm_rot tx_valid tx_in}]
set_load             0.02 $all_out

set_max_fanout    20  [current_design]
set_max_transition 0.5 [current_design]

set_false_path -from [get_ports rst_n]
