#!/usr/bin/env python3
"""Build the RTL timing-optimisation skill document.

Every agent in this repo runs with all tools denied, so a Claude Code skill
cannot be loaded the way skills normally are -- there is no Read tool to load
it with, and giving one back would turn a one-shot call into an agent that
greps the repo. The document is therefore read from disk by the orchestrator
and concatenated into the system prompt.

Two modes, and the mechanical one is the default:

  ``skillgen build``          renders SKILL.md from the committed skill library
                              plus a hand-written preamble. Zero model calls,
                              deterministic, diffable.
  ``skillgen build --llm``    one research call that may consult public
                              documentation on RTL and synthesis optimisation
                              and expand the catalogue. The result is committed
                              to git, so nothing at run time depends on it.

The research call is the only place in this repo where a model is given network
tools. It is deliberately quarantined here rather than routed through
``llm.call``, whose blanket tool denial is load-bearing for the loop's cost
model and must not be relaxed for everything just because one one-off step
needs it.

Whatever the mode, harvested transformations enter ``skills/library.json`` as
seeds: source "seed", zero occurrences, zero confidence. They are suggestions,
and they earn statistics from real runs like anything else. Writing plausible
numbers next to them would be fabricating evidence, and the library's whole
value is that its numbers mean something.
"""

from __future__ import annotations

import json
import os
import shutil
import subprocess
import sys
from pathlib import Path
from typing import Any

sys.path.insert(0, str(Path(__file__).resolve().parent))
import skills as skills_mod  # noqa: E402

ROOT = Path(os.environ.get("ASTRA_ROOT", Path(__file__).resolve().parent.parent))
SKILL_DIR = ROOT / ".claude" / "skills" / "rtl-timing-optimization"
SKILL_PATH = SKILL_DIR / "SKILL.md"

# The document is pasted into every agent's system prompt, N times per
# iteration. Past a few thousand tokens it costs more than it teaches.
BUDGET = 8000

_FRONTMATTER = """\
---
name: rtl-timing-optimization
description: >-
  Structural Verilog transformations that recover setup slack without changing
  function, latency or interface. Use when rewriting RTL against a measured
  critical path.
---
"""

_PREAMBLE = """\
# RTL timing optimisation

Recovering setup slack means removing logic levels between two flops. Nothing
else on this page matters as much as that sentence: a transformation that moves
gates around without shortening the longest path from a launch flop to a
capture flop has not helped, however much better the code looks afterwards.

## The invariants

These are checked by tools after you answer, so there is no benefit in bending
them:

1. **Functional equivalence.** A sequential equivalence check runs against the
   original design. Bit-exact outputs, cycle for cycle. A rewrite that changed
   behaviour is discarded no matter how much slack it recovered.
2. **Latency and interface are fixed.** Same module name, same ports, same
   widths, same pipeline depth. You may redistribute or duplicate registers.
   You may not add or remove a pipeline stage.
3. **Synthesisable Verilog-2005.** No initial blocks, no delays, no testbench
   constructs.

## How to read a critical path

The instance names in an OpenSTA report (`_14637_`, or a long chain like
`acc_out[33]_DFF_X1_Q_D_AOI21_X1_ZN`) are generated by synthesis and carry no
design meaning. The *sequence of cell types* does:

| what you see | what it is |
|---|---|
| a wall of AND/OR feeding a wide reduction | partial-product generation, or a comparison |
| a long run of XOR with AOI/OAI between | carry propagation through an adder |
| repeated MUX cells in series | a priority chain or a select cascade |
| a single stage with fanout in the tens | one net driving a whole datapath |
| delay spread evenly over 80 stages | the depth itself is the problem, not any one cell |

Where the delay sits decides which transformation applies. A path whose delay
is concentrated in five of ninety stages has a local fix; one where it is
spread evenly does not, and needs the structure changed.

## What reliably works

Ordered by how often it recovers real slack:

**Rebalance a serial chain into a tree.** `((a+b)+c)+d` is three adders deep;
`(a+b)+(c+d)` is two. For n terms the depth goes from n-1 to ceil(log2 n), so
the gain grows with every term. This is the single most productive rewrite on
accumulate and reduction logic.

**Move late work off the path.** If a condition is computed *after* a long
arithmetic result and then used to select against it, compute it beside the
arithmetic from the partial results instead. A saturation clamp at the end of a
40-bit accumulate is the textbook case: the overflow condition is decidable
from the operands, not only from the sum.

**Carry-save intermediate sums.** Every full-width add resolves a carry chain.
Keeping a running total as a redundant (sum, carry) pair makes each
intermediate add a constant-depth 3:2 compression and pays for one carry chain
at the very end instead of one per term.

**Replicate a high-fanout driver.** A net driving many loads needs a large
driver or a buffer tree, and both sit on the launching path. Duplicating the
logic that produces it splits the load without changing the value.

**Narrow a comparison to the bits that decide it.** A 40-bit compare against a
constant usually turns on a handful of high bits. So does an equality test
against a sparse constant.

**Retime across existing registers.** Where a pipeline already has stages, work
can be moved between them. The latency must not change -- this redistributes
logic across existing flops, it does not add one.

**Flatten a priority cascade.** A chain of `?:` is a chain of muxes. A one-hot
select decoded in parallel is one mux, and the decode is off the critical path.

## What wastes an iteration

Observed repeatedly, and none of it moves the number:

- Renaming signals, reordering independent statements, adding attributes.
- Restating the same logic with different operators -- synthesis has already
  canonicalised it and will produce the same gates.
- "Optimisations" whose only effect is to move the same gates around.
- Attacking a construct that is not on the critical path. Check the path first;
  an area saving elsewhere does not buy slack here.
- Adding a pipeline stage. It closes timing and fails the check, which is worse
  than not trying, because it also spends an equivalence proof.

## Arguing equivalence

Every rewrite must come with the reason its outputs are bit-identical. Be
specific about two things, because they are where rewrites actually break:

- **Reset.** Does the restructured logic reset to the same values, in the same
  cycle?
- **Width and sign.** Reassociating a sum changes where intermediate values are
  truncated. `(a+b)+c` and `a+(b+c)` are equal in unbounded arithmetic and can
  differ in fixed width if an intermediate overflows. Widen intermediates, or
  say why they cannot overflow.
"""

_CATALOGUE_HEAD = """\
## Transformation catalogue

Each entry pairs a structural pattern with the transformation that addresses
it. **These carry no evidence yet.** They are textbook suggestions, and the
optimisation loop records how each actually fares -- pass rate on the
equivalence check, and whether it beat its siblings -- so a later run can tell
which of them work on real designs. Until then, treat them as candidates.
"""

_FOOTER = """\
## Choosing among them

Prefer the transformation that removes the most logic levels from the *measured*
path. When two are comparable, prefer the one whose equivalence argument is
easier to make: a rewrite that cannot be proven equivalent is worth nothing,
and the proof is run on every candidate.
"""


# ---------------------------------------------------------------------------
# rendering
# ---------------------------------------------------------------------------


def render_doc(lib: skills_mod.SkillLibrary) -> str:
    """The whole document, assembled from the library and the preamble."""
    entries = sorted(lib.all(include_invalid=False),
                     key=lambda e: (e.get("pattern") or ""))
    rows = [_CATALOGUE_HEAD, ""]
    for e in entries:
        rows.append(f"### {e['pattern']}")
        rows.append("")
        rows.append(f"**{e['strategy']}**")
        if e.get("rationale"):
            rows.append("")
            rows.append(e["rationale"])
        if e.get("example"):
            rows.append("")
            rows.append("```verilog")
            rows.extend(str(e["example"]).splitlines()[:14])
            rows.append("```")
        rows.append("")
    return "\n".join([_FRONTMATTER, _PREAMBLE, "\n".join(rows), _FOOTER])


def load_doc(path: Path | None = None) -> str:
    """The skill body, without its frontmatter. Empty when absent.

    Callers degrade rather than fail: the pipeline runs without a skill
    document, it just runs with less guidance.
    """
    p = Path(path or SKILL_PATH)
    try:
        text = p.read_text()
    except OSError:
        return ""
    if text.startswith("---"):
        end = text.find("\n---", 3)
        if end >= 0:
            text = text[end + 4:]
    return text.strip()


def inject(system: str, doc: str, budget: int = BUDGET) -> str:
    """Append the skill document to a system prompt, truncated at a line.

    A system prompt that stops mid-sentence is worse than one that is missing a
    section, so the cut is made at a line boundary and marked, rather than at
    an arbitrary character.
    """
    if not doc:
        return system
    if len(doc) > budget:
        cut = doc.rfind("\n", 0, budget)
        doc = doc[: cut if cut > 0 else budget].rstrip()
        doc += f"\n\n[skill document truncated at {budget} characters]"
    return f"{system}\n\n# Reference: RTL timing optimisation\n\n{doc}"


# ---------------------------------------------------------------------------
# the research call
# ---------------------------------------------------------------------------

RESEARCH_SYSTEM = """\
You are compiling a reference document on RTL timing optimisation for an
automated Verilog-rewriting agent.

Research what established RTL and synthesis optimisation tools actually do to
recover setup slack -- vendor documentation for commercial synthesis and RTL
optimisation flows, open-source synthesis passes, and standard digital design
references. Extract the *transformations*, not the marketing.

Reply with exactly one JSON object and nothing else:

{
  "skills": [
    {
      "pattern": "<the structural bottleneck, at most 10 words, phrased so it
                   applies to a design nobody has seen -- no identifiers from
                   any specific design>",
      "strategy": "<the transformation, at most 10 words>",
      "rationale": "<the mechanism: why this removes logic levels. Two or three
                     sentences.>",
      "example": "<a few lines of generic, synthesisable Verilog-2005 showing
                   the shape of the transformation>"
    }
  ],
  "notes": "<what your sources agreed on, and where they disagreed>"
}

Rules that matter:

- Pattern and strategy are library keys. Two entries that mean the same thing
  must be phrased the same way, or their statistics fragment across near
  duplicates and neither ever accumulates enough evidence to be trusted.
- Only transformations that preserve function, latency and interface. Adding a
  pipeline stage is out of scope: this agent may not change latency.
- Report no success rates, percentages, or trial counts. Every entry enters the
  library untested and earns its statistics from real runs. Numbers you supply
  would be indistinguishable from measured ones and would corrupt the library.
- At most 16 entries. A short catalogue of transformations that genuinely work
  beats a long one padded with restatements."""

RESEARCH_PROMPT = """\
Compile the transformation catalogue described in your instructions.

Context for scoping it: the consuming agent rewrites small Verilog-2005 modules
(tens to hundreds of lines) to close setup timing after synthesis with Yosys
and static timing analysis with OpenSTA on a Nangate45 standard-cell library.
It sees a critical path localised back to RTL lines, and it must return a
complete rewritten file whose behaviour is bit-identical, cycle for cycle.

Existing entries, which you should not merely restate -- add what is missing,
and phrase anything overlapping the same way so it merges rather than forks:

{existing}
"""

# The one call in this repo that gets network tools, and only these.
RESEARCH_TOOLS = "WebSearch,WebFetch"


def research(existing: list[dict[str, Any]], model: str = "opus",
             timeout: int = 900, dry_run: bool = False) -> dict[str, Any]:
    """One research call. Returns the parsed reply, or raises RuntimeError."""
    listing = "\n".join(f"- {e['pattern']} -> {e['strategy']}" for e in existing)
    prompt = RESEARCH_PROMPT.format(existing=listing or "(none)")
    if dry_run:
        return {"prompt": prompt, "system": RESEARCH_SYSTEM, "skills": []}

    exe = shutil.which("claude")
    if not exe:
        raise RuntimeError("`claude` not found on PATH -- install Claude Code, "
                           "or run `skillgen build` without --llm")
    cmd = [exe, "-p", "--output-format", "json", "--model", model,
           "--append-system-prompt", RESEARCH_SYSTEM,
           "--allowedTools", RESEARCH_TOOLS,
           "--strict-mcp-config"]
    try:
        proc = subprocess.run(cmd, input=prompt, capture_output=True,
                              text=True, timeout=timeout)
    except subprocess.TimeoutExpired as e:
        raise RuntimeError(f"research call timed out after {timeout}s") from e
    if proc.returncode != 0:
        raise RuntimeError(f"claude exited {proc.returncode}: "
                           f"{(proc.stderr or '').strip()[:300]}")
    try:
        res = json.loads(proc.stdout)
    except json.JSONDecodeError as e:
        raise RuntimeError(f"unparsable output: {proc.stdout[:300]}") from e
    if res.get("is_error"):
        raise RuntimeError(f"claude reported an error: "
                           f"{str(res.get('result', ''))[:300]}")

    import drrtl                                     # noqa: PLC0415 -- cycle
    parsed = drrtl.extract_json(str(res.get("result", ""))) or {}
    u = res.get("usage") or {}
    parsed["_usage"] = {
        "input_tokens": u.get("input_tokens"),
        "output_tokens": u.get("output_tokens"),
        "cost_usd": res.get("total_cost_usd"),
    }
    return parsed


def ensure_seeds(lib: skills_mod.SkillLibrary,
                 entries: list[dict[str, Any]]) -> list[str]:
    """Add harvested transformations as seeds. Never as evidence."""
    added: list[str] = []
    for e in entries[:16]:
        pattern, strategy = (e.get("pattern") or "").strip(), (e.get("strategy") or "").strip()
        if not pattern or not strategy:
            continue
        before = len(lib)
        entry = lib.add_seed(pattern, strategy, e.get("rationale", ""),
                             e.get("example", ""))
        if len(lib) > before:
            added.append(entry["id"])
    return added


# ---------------------------------------------------------------------------
# cli
# ---------------------------------------------------------------------------


def main(argv: list[str]) -> int:
    import argparse
    ap = argparse.ArgumentParser(
        prog="astra-skilldoc",
        description="Build the RTL timing-optimisation skill document.")
    ap.add_argument("action", nargs="?", default="build",
                    choices=("build", "show", "path"))
    ap.add_argument("--llm", action="store_true",
                    help="one research call that may consult public sources")
    ap.add_argument("--model", default="opus")
    ap.add_argument("--timeout", type=int, default=900)
    ap.add_argument("--dry-run", action="store_true",
                    help="print the research prompt and call nothing")
    ap.add_argument("--force", action="store_true",
                    help="overwrite an existing SKILL.md")
    ap.add_argument("--skills", type=Path, default=None)
    args = ap.parse_args(argv[1:])

    if args.action == "path":
        print(SKILL_PATH)
        return 0
    if args.action == "show":
        doc = load_doc()
        print(doc or "(no skill document -- run: astra skilldoc build)")
        return 0

    lib = skills_mod.SkillLibrary(args.skills)

    if args.llm:
        try:
            parsed = research(lib.all(True), args.model, args.timeout, args.dry_run)
        except RuntimeError as e:
            print(f"[skillgen] ERROR: {e}", file=sys.stderr)
            return 1
        if args.dry_run:
            print(parsed["system"])
            print("\n" + "=" * 70 + "\n")
            print(parsed["prompt"])
            print(f"\n[skillgen] dry run: ~{len(parsed['prompt']) // 4} prompt "
                  f"tokens, nothing called")
            return 0
        added = ensure_seeds(lib, parsed.get("skills") or [])
        lib.save()
        print(f"[skillgen] harvested {len(parsed.get('skills') or [])} "
              f"transformation(s), {len(added)} new seed(s) in {lib.path}")
        if parsed.get("notes"):
            print(f"[skillgen] notes: {parsed['notes']}")
        u = parsed.get("_usage") or {}
        if u.get("cost_usd") is not None:
            print(f"[skillgen] 1 call, in {u.get('input_tokens')} "
                  f"out {u.get('output_tokens')}, notional ${u['cost_usd']:.4f}")

    if SKILL_PATH.is_file() and not args.force and not args.llm:
        print(f"[skillgen] {SKILL_PATH} already exists; --force to rebuild")
        return 0

    SKILL_DIR.mkdir(parents=True, exist_ok=True)
    SKILL_PATH.write_text(render_doc(lib))
    print(f"[skillgen] wrote {SKILL_PATH} "
          f"({len(SKILL_PATH.read_text())} chars, {len(lib)} catalogue entries)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
