# ---------------------------------------------------------------------------
# dual_clock timing constraints -- two asynchronous domains.
#
# The clock block below is generated by tools/clocks.py from the `clocks` list
# in config.json: a create_clock per master, a create_generated_clock for the
# divider, and the set_clock_groups that keeps the crossing out of setup
# analysis. See docs/multi-clock.md.
# ---------------------------------------------------------------------------
@ASTRA_CLOCK_DEFS@

foreach c [all_clocks] {
    set_clock_uncertainty 0.05 $c
    set_clock_transition  0.05 $c
}

# OpenSTA 3.1.0 cannot parse a bus subscript in a get_ports pattern
# (`get_ports {f_a[*]}` dies with a bare `Error: stoi`), so ports are selected
# by walking the collection and matching the name in Tcl. See HANDOFF.md §7.
proc astra_ports {collection bases} {
    set out {}
    foreach p $collection {
        set n [get_full_name $p]
        foreach b $bases {
            if {$n eq $b || [string match "${b}\[*" $n]} { lappend out $p; break }
        }
    }
    return $out
}

set all_in  [all_inputs]
set all_out [all_outputs]

set_input_delay  -clock clk_fast [expr {@CLK_PERIOD:clk_fast@ * 0.15}] \
    [astra_ports $all_in {f_valid f_a f_b}]
set_input_delay  -clock clk_slow [expr {@CLK_PERIOD:clk_slow@ * 0.15}] \
    [astra_ports $all_in {s_req}]

set_output_delay -clock clk_fast [expr {@CLK_PERIOD:clk_fast@ * 0.15}] \
    [astra_ports $all_out {f_acc}]
set_output_delay -clock clk_slow [expr {@CLK_PERIOD:clk_slow@ * 0.15}] \
    [astra_ports $all_out {s_grant s_any}]

set_input_transition 0.05 [astra_ports $all_in {f_valid f_a f_b s_req}]
set_load             0.02 $all_out

set_max_fanout    20  [current_design]
set_max_transition 0.5 [current_design]

set_false_path -from [get_ports rst_n]
